# Generated by Django 3.0.2 on 2021-01-22 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='news',
            table='News',
        ),
    ]
